In [2]:
import numpy as np
x = np.array([5, 1, 9, 8, 7])

In [3]:
#Method 1: Sum of all the elements of an array
x.sum()


30

In [4]:
#Method 2: Minimum value among the elements of an array
x.min()

1

In [5]:

#Method 3: Maximum value among the elements of an array
x.max()

9

In [6]:
#Method 4: Minimum index value among the indexes of elements of an array
x.argmin()

1

In [12]:
#Method 5: Minimum index value among the indexes of elements of an array
x.argmax()

2

In [11]:
#Mehthod 6: Logical "AND" operation among the elements of a boolean array
np.all([False, True, True, True])

False

In [13]:
#Mehthod 7: Logical "OR" operation among the elements of a boolean array
np.any([True, True, True, False])

True

In [14]:
#Method 8: Setting all the elements of an array to 0
a = np.zeros((100, 100))
np.any(a != 0)

False

In [15]:
np.all(a == a)

True

In [17]:

a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [18]:
np.all(a == b)


False

In [21]:

#Method 9: Setting diagonally all elements as "1" in a square matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#Method 10: diag: This function creates a two dimensional 
#array with all the diagonal elements as the given value
#and rest as 0 (in a square matrix).
arr = np.diag([1,5,3,7])
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [24]:
#To get the diagonal elements in a two dimensional array we
#use diag as a funcion
np.diag(arr)

array([1, 5, 3, 7])

In [25]:
#Method 11: randint. This funciton is used to generate random
#number between a given range.
#The syntax is:
#randint(min,max,total_values)
arr = np.random.randint(1,10,3)
arr
#output would be any 3 number from 1 to 9

array([2, 2, 5])

In [26]:
#Method 12: rand: This function is used to generate random values
#between 0 to 1
#The syntax is: 
#rand(number_of_values)
arr = np.random.rand(5)
arr
#Output may be any 5 numbers from 0 to 1

array([0.18153592, 0.96573983, 0.14606861, 0.30600873, 0.62790149])

In [ ]:

#...continues. We may generate random numbers in 2D array format as well
arr = np.random.rand(2, 3)

In [27]:
#Method 13: randn: This function is used to generate random values to 0 (zero)
#This may return positive or negative numbers as well.
#The syntax is:
#randn(number_of_values)
arr = np.random.randn(5)
arr
#Output may be any 5 numbers from centered to 0 (zero)

array([-2.46412417,  1.27502498,  0.94896794, -0.90843231,  0.34000711])

In [28]:
#Method 14: arange. There would be a starting point and an ending point along
#with the interval value.
arr = np.arange(2,15,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [30]:

#...continues. If we do not specify the value it will automatically be incremented by 1
arr = np.arange(2, 14)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:

#Method 15: sin. Print sine of one angle:
np.sin(np.pi/2.)

1.0

In [33]:
#...continues. Print sines of an array of angles given in degrees:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [34]:
#Method 16: cos.
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [37]:
#Method 16: tan
from math import pi
np.tan(np.array([-pi,pi/2,pi])

SyntaxError: unexpected EOF while parsing (<ipython-input-37-337d7eb81524>, line 3)

In [38]:
#Method 17: round.
np.round(16.055, 2), round(16.055, 2)  # equals 16.0549999999999997

(16.06, 16.05)

In [39]:
#Method 18: floor. Return the floor of the input, element-wise.
#The floor of the scalar x is the largest integer i, such that i <= x.
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [41]:
#Method 19: ceil. Return the ceiling of the input, element-wise.
#The ceil of the scalar x is the smallest integer i, such that i >= x.
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [43]:
#Method 20:
#Return the truncated value of the input, element-wise.
#The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. 
#In short, the fractional part of the signed number x is discarded.
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [44]:
#Method 21: Prod.
#Return the product of array elements over a given axis.
#The product of an empty array is the neutral element 1:
np.prod([])

1.0

In [46]:
#...continues. when the input array is two-dimensional:
np.prod([[1.,2.],[3.,4.]])

24.0

In [47]:
#Method 22: cumsum. Return the cumulative sum of the elements along a given axis.
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
#Method 23: lcm. Returns the lowest common multiple of |x1| and |x2|
np.lcm(12, 20)

60

In [50]:
#Method 24: gcd. Returns the greatest common divisor of |x1| and |x2|
np.gcd(12, 20)

4

In [51]:
#Method 25: transpose. Reverse or permute the axes of an array; returns the modified array
x = np.arange(4).reshape((2, 2))
x

array([[0, 1],
       [2, 3]])

In [52]:

#Method 26: capitalize. Return a copy of a with only the first character of each element capitalized.
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [53]:
#Method 27. lower. Return an array with the elements converted to lowercase.
c = np.array(['A1B C', '1BCA', 'BCA1']) 
c

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

In [54]:
#Method 28. upper. Return an array with the elements converted to upper.
c = np.array(['a1b c', '1bca', 'bca1'])
c

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [55]:
#Method 29. count. Returns an array with the number of non-overlapping occurrences of substring sub in the range [start, end].
#Calls str.count element-wise.
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [56]:

#Method 30. linspace. This function returns values 
#between a given range and with a same gap between
#consecutive elements.
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [57]:

#Method 31,32,33,34
matrix = np.random.randint(1,4,9).reshape(3,3)
matrix

array([[3, 2, 3],
       [3, 2, 2],
       [2, 1, 2]])

In [59]:
#Method 35. shuffle. shuffle the array elements.
np.random.seed(122)
arr = np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [60]:
#Method 36. unique. displays unique number of the array.
np.unique(arr)

array([ 3, 10, 11, 13, 16, 17])

In [61]:
#Method 37. argsort. prints the sorted index value wise ascending
one = np.array([1,3,4,2])
one.argsort()

array([0, 3, 1, 2], dtype=int64)

In [62]:
#Method 38. where.
x = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
#Method 39. count_nonzero
np.count_nonzero(arr)

8

In [64]:
#Method 40. sort. It is used to sort an array
a = np.array([[1,4], [3,1]])
a

array([[1, 4],
       [3, 1]])

In [65]:
#Method 41. variance. var.
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

In [67]:
#Method 42. Split. Split an array into 
#multiple sub-arrays as views into ary.
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [68]:

#Method 43. delete. Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those
#entries not returned by arr[obj].
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
#Method 44. insert. insert values along the 
#given axis before the given indices.
a = np.array([[1,1],[2,2],[3,3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [72]:
#Method 45. fliplr. Flip array in the left/right direction.
#Requires the array to at least 2-D.
A = np.diag([1.,2.,3.])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [73]:
#Method 46. flipud. Flip array in the up/down direction.
#Does not require the array to be two-dimensional.
A = np.diag([1.0, 2, 3])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [75]:

#Method 47. inner. Inner product of two arrays.
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [76]:

#Method 48. Return the sum along diagonals of the array.
np.trace(np.eye(3))

3.0

In [77]:
#Method 49. reciprocal. Return the reciprocal of the argument, element-wise.
#This function is not designed to work with integers.
np.reciprocal(2.)

0.5

In [78]:

#Method 50. conjucate. Return the complex conjugate, element-wise.
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])